### ISSUE TITLE
Error: useEffect Hook not returning properly

### ISSUE THREAD

**Issue by smithd36** [smithd36/smithd36.github.io#1]
Error on local server returning errors related to a hook & index error when navigating" Contact -> Home OR Contact -> About
/*
Uncaught runtime errors:
ERROR
destroy is not a function
TypeError: destroy is not a function
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:64611:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:64749:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:66430:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:66386:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:66308:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:66296:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:68119:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:68072:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:68031:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:67814:9)
ERROR
destroy is not a function
TypeError: destroy is not a function
    at safelyCallDestroy (http://localhost:3000/static/js/bundle.js:64611:9)
    at commitHookEffectListUnmount (http://localhost:3000/static/js/bundle.js:64749:15)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:3000/static/js/bundle.js:66430:15)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:3000/static/js/bundle.js:66386:9)
    at commitPassiveUnmountEffects_begin (http://localhost:3000/static/js/bundle.js:66308:15)
    at commitPassiveUnmountEffects (http://localhost:3000/static/js/bundle.js:66296:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:68119:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:68072:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:68031:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:67814:9)
*\

**Comment by smithd36** [comment]
Applied fix to Contact page: 
Old code:
"""
  useEffect(() => {
    return setTimeout(() => {
      setLetterClass('text-animate-hover')
    }, 3000)
  }, [])
"""

NEW CODE:
"""
useEffect(() => {
  const timeoutId = setTimeout(() => {
    setLetterClass('text-animate-hover');
  }, 3000);

  return () => {
    clearTimeout(timeoutId);
  };
}, []);

"""

Closing TIcket #1
